application: nucalendarfeed
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /linkedin.*
  script: main.py
- url: /oauth2callback.*
  script: main.py
- url: /calendarnews
  script: main.py
- url: /static
  static_dir: static
